new branch modified
Basma-Abdallah/laravelr6 pull request #1
Opened 2024-07-16 22:12 UTC by Basma-Abdallah

2024-07-17 06:30 UTC, Nora-Lootfy requested changes
You have done it the hard way,, try to search how to do it with Laravel it is much simpler but your code still do the job,, good job ya Basma

2024-07-24 08:22 UTC, Nora-Lootfy commented on app/Http/Controllers/ClassController.php
> +      $className=$request->className;
try using associative array rather than lots of variables,, it is more cleaner

2024-07-24 08:22 UTC, Nora-Lootfy approved these changes
Good job ya Basma, you have nailed it

2024-07-28 08:50 UTC, Nora-Lootfy commented on app/Http/Controllers/ClassController.php
> +    return redirect('classes');
you have forget to add trashed classes function and file

2024-07-28 08:51 UTC, Nora-Lootfy requested changes
good job ya Basma

2024-07-31 00:41 UTC, Nora-Lootfy commented on app/Http/Controllers/ClassController.php
> +         'timeFrom'=>'required|date_format:H:i',
check that timeFrom is before timeTo

2024-07-31 00:43 UTC, Nora-Lootfy approved these changes
Close the pull request ya Basma, after i review it then open a new on after every task submitting

Have a nice day😊

2024-07-31 16:03 UTC, Basma-Abdallah commented on app/Http/Controllers/ClassController.php
> +         'timeFrom'=>'required|date_format:H:i',
'strtotime($class->timeFrom)'=>'date_format:H:i',
             'strtotime($class->timeTo)'=>'date_format:H:i|after:timeFrom'
        

i did code like this but I don't know why these changes didn't appear in the last commit

2024-07-31 16:52 UTC, merged